### ISSUE TITLE
mouse input

### ISSUE THREAD

**Issue by welford** [welford/qurp#1]
Current version has no support for the mouse.

**Comment by kramble** [comment]
Mouse support is now done. Just using event input, so no dependency on X-Windows or SDL (still needed for sound though).

It's a bit clunky, so you may want to tidy it up a bit (the code really needs to be in in_rpi.c not gl_vidrpi.c but that's where the original stuff was). I've also hacked around with platform.pi.c quite badly, sorry.

**Comment by kramble** [comment]
Ah, it's not quite working fully. It was ok with the mouse on /dev/input/event0 and keyboard on event1, but with them swapped over, it does not see the mouse at all. Not sure what's going on here as it ought not to matter. Will investigate.

**Comment by welford** [comment]
ok, feel free to move it to in_rpi.c, I believe input code is only in gl_vidrpi.c because i was using gl_vidlinux.c as my template when making the raspberry pi port.

Are you going to make pull requests for your changes?

**Comment by kramble** [comment]
Yep, my changes are pretty much complete (there is still an outstanding issue of keyup events occasionally being missed, but that can wait).

Looking at your most recent commit,there are only a couple of clashes. I added #include <stdio.h> to modern_gles_port.c to fix a compile warning, so that can be reverted, and I just need to add support for your RELEASE_BUILD in platform.pi.c. I'll do that right now, then I think I'll just create a pull request for the whole package, which leaves you with the problem of deciding how to merge it.
Alternatively I can resync my fork with yours, reapply my commits where they don't clash, then raise a pull request on that, but I'm much of a github expert, so that may be more of a problem.
Anyway I'll get on with the RELEASE_BUILD change for now
