### ISSUE TITLE
Console commands not recognized, config.txt not created or edited

### ISSUE THREAD

**Issue by Antiriad** [welford/qurp#13]
Hi,
on my RPi 3 Qurp does not save any option 'cause of missing config.txt.
Even if I create new config.txt file in ID1 folder, still Qurp does not save settings.
Also a lot of console commands are not recognized and it seems there is no way to save the display mode selected with "-width" and "-height" options in CLI.
Thanks

**Comment by welford** [comment]
What are the console commands that are not recognized?

**Comment by welford** [comment]
reproduce quake not saving files, not sure what missing config.txt means though.

**Comment by Antiriad** [comment]
Hi welford, 
Quake should create a config.txt file in ID1 folder to store all the player settings (mouse and keyboard controls, video and audio preferences etc.) but this does not happens with Qurp, at least on my RPi 3.
So settings and preferences from main menu are not saved.

About console commands: a lot of console commands described [here](http://www.quakewiki.net/archives/console/commands/quake.html) are not recognized, and _vid_mode_ is ignored at all.

So the only way to run Qurp at a desired resolution is with -width and -height options in CLI, without the possibility to save resolution settings. 

Thank you.

**Comment by welford** [comment]
Hello,

In quro vid_mode is not as applicable as it would be in the windows
versions. There is 1 video mode and the user can only switch the
resolutions. I'll look to adding some commands for setting the resolution
via the config file  e.g. vid_with & vid_height.

Also could you give me a list of specific commands that you want to use
that don't appear to be supported? I don't want to test every single
console command.

Thanks :)



On 10 Apr 2017 13:23, "Antiriad" <notifications@github.com> wrote:

Hi welford,
Quake should create a config.txt file in ID1 folder to store all the player
settings (mouse and keyboard controls, video and audio preferences etc.)
but this does not happens with Qurp, at least on my RPi 3.
So settings and preferences from main menu are not saved.

About console commands: a lot of console commands described here
<http://www.quakewiki.net/archives/console/commands/quake.html> are not
recognized, and *vid_mode* is ignored at all.

So the only way to run Qurp at a desired resolution is with -width and
-height options in CLI, without the possibility to save resolution settings.

Thank you.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/welford/qurp/issues/13#issuecomment-292933835>, or mute
the thread

**Comment by Antiriad** [comment]
Hello and thank you for your feedback.
IMHO if Qurp could save controls and video settings (resolution) from main menu in config.txt, console commands are not needed at all.

Thanks

**Comment by welford** [comment]
https://github.com/welford/qurp/commit/89a5428c5f37ec2f96413e24cd26705aebacb74f

-Qurp should now save config.cfg on exiting the game (options -> quit -> y)
-Added VID_HEIGHT & VID_WIDTH which can be set from the console and will be applied the next time you restart Qurp (raspberry pi edition only)
