### ISSUE TITLE
no sound effects

### ISSUE THREAD

**Issue by welford** [welford/qurp#3]
currently nothing plays

**Comment by kramble** [comment]
I've done a quick hack to get sound working via SDL. It needs tidying up so I'm not going to git-pull it as it stands, but you might want to take a look at it.

**Comment by welford** [comment]
Thanks! I was kind of hoping to get this all working without SDL though given the frequency at which I am currently able to work on this  it may be better to include it until something else can replace it.

**Comment by kramble** [comment]
You're welcome. I've not got much experience with SDL (just started on this yesterday), so my hack is probably a bit ropey. i noticed that the quake3 code uses SDL too, but they do a lot more checking and stuff, so I rolled my version from scratch. I may take a look at how they do the keyboard/mouse input and see if I can get that ported over too (I think it relies on running under X).

I also noticed that the game crashes quite horribly sometimes (does not clean up the video driver), not sure if that is my doing with SDL or not. Will look into it.

**Comment by welford** [comment]
Oh, I've never seen the game crash horribly before. Is it seemingly at random? There were buffer overflow crashes before but it didn't kill the rpi also.

I don't think we need SDL for KB/Mouse input (not sure if that is what you are suggesting) I was looking at that code a few weeks back and it shouldn't be difficult to get better support using some simple changes.

**Comment by kramble** [comment]
I've tried to replicate this, and it does seem to be my fault (though the original non-SDL game does still crash occasionally). The graphics hangs and you need to ctrl-c to quit, but I think this is failing to clean up SDL (it leaves a thread running which can't be killed, and attempting to reboot just hangs the rpi). This was running under X-windows. I haven't checked it running from the console shell without x-windows yet. I'm also using a very old sdcard debian image (two years old!) so there may be some update-related bugs there.

So it's not actually a video issue I think. Probably need to call SDL_CloseAudio via atexit or something like that. I did say my code was a bit crude!

On the keyboard/mouse, yeah, I just thought that since I was using SDL already, it would be easiest to just copy the quake 3 methodology (once I've worked out exactly how they go about doing input). It would be better to avoid it though. I have already made a small tweak to the platform.pi.c code as my keyboard was appearing on the wrong ./dev/input/event channel.

Anyway I'll poke around with this a bit more and see it I can get that SDL cleanup issue fixed.

**Comment by kramble** [comment]
Sorry, my bad, I only had 64MB of gpu_mem in /boot/config.txt. I changed it to 128MB and it's running stable now, no crashes.

**Comment by welford** [comment]
Understood. I guess you are right about the SDL stuff. It's the quickest and easiest option at the moment and then the game should be in a much more complete looking state.
