### ISSUE TITLE
Weird Bug on Raspberry Pi 1

### ISSUE THREAD

**Issue by CelestiorTheGreat** [welford/qurp#9]
Hello welford,
I built the qurp project on my raspberry pi 1 (Model B) and was running into some issues. The entire building process worked fine without any errors, but when I try and launch the game, it freaks out and doesn't render the world properly. It's really hard to explain stuff like this through text, so I uploaded this unlisted video to YouTube to show what I mean:

https://youtu.be/zcCcejf1Ib8

I hope you can do something with this information, because I'd love to use your sourceport on the pi :)

**Comment by welford** [comment]
Hello,

Could you try running this from the command line? I.e. log out of the
desktop mode and run the game from there. I've never tested it when running
within the desktop.

Do you have your memory split to 128?

If that doesn't work let me know

Btw, this is currently GL quake only, I've tried to make it look similar to
the software version.

On 20 Sep 2016 1:37 p.m., "CelestiorTheGreat" <notifications@github.com>
wrote:

Hello welford,
I built the qurp project on my raspberry pi 1 (Model B) and was running
into some issues. The entire building process worked fine without any
errors, but when I try and launch the game, it freaks out and doesn't
render the world properly. It's really hard to explain stuff like this
through text, so I uploaded this unlisted video to YouTube to show what I
mean:

https://youtu.be/zcCcejf1Ib8

I hope you can do something with this information, because I'd love to use
your sourceport on the pi :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/welford/qurp/issues/9>, or mute the thread

**Comment by CelestiorTheGreat** [comment]
Hi, thanks for the quick reply.
Unfortunately it didn't work. I set the pi to boot to CLI and launched both debug and release versions. Somehow the release version didn't find theh pak files, since it couldn't load gfx.wad, but the debug version launched. It had the same issue as berfore though...

I'll try to recompile them from the CLI next. Maybe that'll do it.

**Comment by CelestiorTheGreat** [comment]
![14408825_1153867928011851_412667335_n](https://cloud.githubusercontent.com/assets/22320201/18672552/dde2ae2c-7f48-11e6-8609-4b4c4a026f4e.jpg)

I realised that sometimes during building it would show these warnings. Not sure if that is an issue or not..

**Comment by welford** [comment]
That is not an issue. Also both the release and debug builds should work.

I can't look at this right now but I am making this on a pi 1 model b too
and it was OK for me this weekend, will double check when I have time.

**Comment by CelestiorTheGreat** [comment]
Oh wait, I just saw that you wanted me to change the memory split derp.
I changed it to 128 and it worked!! Thanks alot :D

**Comment by welford** [comment]
Glad to hear that, let me know of any other bugs you come across.
